import Head from 'next/head'
import Image from 'next/image'

import Headers from '../components/Headers'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'


export default function Home({result}) {
  console.log();
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

{/* Headers */}
<Headers />

{/* Nav */}

<Nav />

{/* Results  */}

<Results result={result }/>

    </div>
  )
}

export async function getServerSideProps(context) {
  
  const genre = context.query.genre
  console.log('heeee', `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTopRated.url}`);
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTopRated.url}`)
  const result = await request.json()

  console.log('here', result);
  return {
    props: {
      result
      
    }
    
  }
  
}